### ISSUE TITLE
Selgros- The message " Romania is not a city in Romania" is displayed

### ISSUE THREAD

**Issue by AdinaIT** [peviitor-ro/based_scraper_py#240]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Run scraper for "Selgros" Company
3. Open the link https://selgros.mingle.ro/ro/embed/apply
4. Check the jobs location: "Asistent (a) Relații clienți" ; "Lucrător depozit Picker" ; "HR Specialist (Ilfov)" and "Director adjunct magazin"

EXPECTED RESULTS:
The location should contain: the city also the place where the store is located like on the company's website

ACTUAL RESULTS:

On the scrapers.peviitor.ro the message of jobs location:  " Bucuresti - Pantelimon is not a city in Romania" or " Bucuresti - Drumul Taberei is not a city in Romania"  and "Romania is not a city in Romania" is displayed

For the job "Director adjunct magazin" the location doesn't appear on the company's website

![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/b2fd9f77-8a14-4fc6-ada7-3f2079035cc5)
![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/b4ecf8b9-d556-41a8-873e-a6e6f54eb0bb)

![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/81b002c8-fb7f-43d6-9ced-cfab6c6f174b)
![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/b310a86a-f739-4f47-91e0-fcc9251b5cc8)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdinaIT** [comment]
Retesting. 
On the company's website, the position of "Assistant(a) Relatii clienti" is no longer open.
At the position of "Director adjunct magazin", the location still doesn't appear.
On the https://scrapers.peviitor.ro, the problem can be considered solved.
